talk:
  texture: default/chat/talk
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":talk:"
    permission: "oraxen.emoji.talk"

shop:
  texture: default/chat/shop
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":shop:"
    permission: "oraxen.emoji.shop"

info:
  texture: default/chat/info
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":info:"
    permission: "oraxen.emoji.info"

warp:
  texture: default/chat/warp
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":warp:"
    permission: "oraxen.emoji.warp"

donate:
  texture: default/chat/donate
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":donate:"
    permission: "oraxen.emoji.donate"

pshop:
  texture: default/chat/pshop
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":pshop:"
    permission: "oraxen.emoji.pshop"

kits:
  texture: default/chat/kits
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":kits:"
    permission: "oraxen.emoji.kits"

alchemist:
  texture: default/chat/alchemist
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":alchemist:"
    permission: "oraxen.emoji.alchemist"

tinkerer:
  texture: default/chat/tinkerer
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":tinkerer:"
    permission: "oraxen.emoji.tinkerer"

enchanter:
  texture: default/chat/enchanter
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":enchanter:"
    permission: "oraxen.emoji.enchanter"

battlepass:
  texture: default/chat/battlepass
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":battlepass:"
    permission: "oraxen.emoji.battlepass"

reforge:
  texture: default/chat/reforge
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":reforge:"
    permission: "oraxen.emoji.reforge"

vault:
  texture: default/chat/vault
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":vault:"
    permission: "oraxen.emoji.vault"

server:
  texture: default/chat/server
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":server:"
    permission: "oraxen.emoji.server"

bank:
  texture: default/chat/bank
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":bank:"
    permission: "oraxen.emoji.bank"

trader:
  texture: default/chat/trader
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":trader:"
    permission: "oraxen.emoji.trader"

quest:
  texture: default/chat/quest
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":quest:"
    permission: "oraxen.emoji.quest"

auction:
  texture: default/chat/auction
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":auction:"
    permission: "oraxen.emoji.auction"

market:
  texture: default/chat/market
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":market:"
    permission: "oraxen.emoji.market"

menu:
  texture: default/chat/menu
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":menu:"
    permission: "oraxen.emoji.menu"

jobs:
  texture: default/chat/jobs
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":jobs:"
    permission: "oraxen.emoji.jobs"

security:
  texture: default/chat/security
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":security:"
    permission: "oraxen.emoji.security"

peddler:
  texture: default/chat/peddler
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":peddler:"
    permission: "oraxen.emoji.peddler"

merchant:
  texture: default/chat/merchant
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":merchant:"
    permission: "oraxen.emoji.merchant"

keysmith:
  texture: default/chat/keysmith
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":keysmith:"
    permission: "oraxen.emoji.keysmith"

exchange:
  texture: default/chat/exchange
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":exchange:"
    permission: "oraxen.emoji.exchange"

rewards:
  texture: default/chat/rewards
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":rewards:"
    permission: "oraxen.emoji.rewards"

cosmetics:
  texture: default/chat/cosmetics
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":cosmetics:"
    permission: "oraxen.emoji.cosmetics"

rankup:
  texture: default/chat/rankup
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":rankup:"
    permission: "oraxen.emoji.rankup"

doctor:
  texture: default/chat/doctor
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":doctor:"
    permission: "oraxen.emoji.doctor"

tags:
  texture: default/chat/tags
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":tags:"
    permission: "oraxen.emoji.tags"

petshop:
  texture: default/chat/petshop
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":petshop:"
    permission: "oraxen.emoji.petshop"

statistic:
  texture: default/chat/statistic
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":statistic:"
    permission: "oraxen.emoji.statistic"

faction:
  texture: default/chat/faction
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":faction:"
    permission: "oraxen.emoji.faction"

tutorial_guide:
  texture: default/chat/tutorial_guide
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":tutorial_guide:"
    permission: "oraxen.emoji.tutorial_guide"

event_guide:
  texture: default/chat/event_guide
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":event_guide:"
    permission: "oraxen.emoji.event_guide"

town_elder:
  texture: default/chat/town_elder
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":town_elder:"
    permission: "oraxen.emoji.town_elder"

scholar:
  texture: default/chat/scholar
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":scholar:"
    permission: "oraxen.emoji.scholar"

engineer:
  texture: default/chat/engineer
  ascent: 8
  height: 8
  chat:
    placeholders:
      - ":engineer:"
    permission: "oraxen.emoji.engineer"
